#!/bin/sh
set -x

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc
ln -sf /proc/mounts /etc/mtab

echo "Loading, please wait..." > /dev/tty1

if ! mount -t devtmpfs -o nosuid,mode=0755 udev /dev; then
	echo "W: devtmpfs not available, falling back to tmpfs for /dev"
	mount -t tmpfs -o nosuid,mode=0755 udev /dev
	[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
	[ -e /dev/null ] || mknod /dev/null c 1 3
fi

mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run
mkdir -m 0755 /run/initramfs

# echo "first shell" > /dev/tty1
# /bin/sh < //dev/tty1 > /dev/tty1

export init=/sbin/init
# export quiet=n
export rootmnt=/root
# echo "second shell" > /dev/tty1
# /bin/sh < /dev/tty1 > /dev/tty1

echo "mount /root" > /dev/tty1
mount /dev/mmcblk0p3 ${rootmnt}

# test -d ${rootmnt}/ubuntu-16.04.1.lts && mount --bind ${rootmnt}/ubuntu-16.04.1.lts /ubuntu

echo "move dev etc to /root" > /dev/tty1

move_dirs()
{
  rootmnt=$1
  udevadm control --exit
  mount -n -o move /dev ${rootmnt}/dev
  rm -rf /dev
  ln -s ${rootmnt}/dev /dev
  mount -n -o move /run ${rootmnt}/run
  mount -n -o move /sys ${rootmnt}/sys
  mount -n -o move /proc ${rootmnt}/proc
}

# echo "third shell" > /dev/tty1
# /bin/sh < /dev/tty1 > /dev/tty1
echo "run-init" > /dev/tty1

boot_distro ()
{
  distro=$1
  mnt=$2
  mount --bind ${distro} ${mnt}
  rootmnt=${mnt}
  move_dirs ${rootmnt}
  cd ${rootmnt}
  pivotroot . initrd
  exec chroot . ${init} <dev/console >dev/console 2>&1
}
  
# ubuntu OK
# boot_ubuntu 
echo "" > /dev/tty1
echo "Choose os to boot " > /dev/tty1
echo "	enter 1 for Slackware 14.2" > /dev/tty1
echo "  enter 2 for Ubuntu " > /dev/tty1
echo "  enter 3 for Slackware setup " > /dev/tty1
echo "  any other for Slackware 14.2" > /dev/tty1
echo "        " > /dev/tty1
# default, slackware, 10 seconds timeout.
ans=1
read -t 10 ans </dev/tty1 >/dev/tty1 2>&1

case $ans in 
	'1')
		boot_distro /root/slackware-14.2 /slackware
	;;
	'2')
		boot_distro /root/ubuntu-16.04.1.lts /ubuntu
	;;
	'3')
		boot_distro /root/slackware-14.2.setup /slackware
	;;
	*)
		boot_distro /root/slackware-14.2 /slackware
	;;
esac

echo "Something went badly wrong in the initramfs."
panic "Please file a bug on initramfs-tools."

